### ISSUE TITLE
Let's find someone who can upload a Safari version to the Safari extensions repository

### ISSUE THREAD

**Issue by unforgettableid** [mahfoozm/YorkURMP#7]
Dear @Aayush9029:

I did some Google searching, hoping to find a York student who already has a paid Apple Developer account.  It looks like you qualify.

Would you be willing to please upload a Safari version of the open-source [YorkURMP](https://github.com/mahfoozm/YorkURMP) extension to the official Safari extensions repository?

@mahfoozm doesn't have an Apple Developer account, and understandably doesn't want to pay for one.

Thank you for reading this!

**Comment by Aayush9029** [comment]
@unforgettableid 

Thank you for considering me for your request. After careful consideration, I regret to inform you that I am unable to upload the **YorkURMP** extension to the official Safari extensions repository under my name. This is primarily due to the additional work and responsibilities involved in publishing an app under my developer account.

However, I would be willing to assist in compiling, notarizing and signing any open-source macOS application created to help students, provided that the developer takes care of the distribution process.

I apologize for any inconvenience this may cause, and I appreciate your understanding.

**Comment by unforgettableid** [comment]
Superseded by issue 8.  Closing as duplicate.
